### ISSUE TITLE
Please expand readme with an explanation

### ISSUE THREAD

**Issue by ADTC** [RubaXa/wormhole#11]
I'd love to see an explanation for the following questions (in the Readme, **_not here_**):

1. What real-world problem does this library attempt to solve?
1. What inspired the creation of this library?
1. Couldn't I do the same thing with cookies and some simple scripts to read them?

**Comment by RubaXa** [comment]
In fact, there are answers to all these questions:
1. Is EventEmitter for communication between tabs with Master/slave
2. Need for communication between tabs ;] (for example, to support one WebSocket connection)
3. Maybe, but I do not know how to make it easier.

**Comment by ADTC** [comment]
I hope you understand what I mean with Q1/2. Allow me to give a simple analogy.

A kettles boils water. But the real-world problem the kettle solves is _not_ that water needs to be boiled. It's that someone wants to have a hot cup of tea, for which hot water is necessary.

So what would be the tea here?

**Comment by RubaXa** [comment]
Alas, I do not understand what you mean.
