### ISSUE TITLE
Add SharedWorker documentation

### ISSUE THREAD

**Issue by arypurnomoz** [RubaXa/wormhole#4]
It will be very nice if the SharedWorker feature is documented.

**Comment by RubaXa** [comment]
https://github.com/RubaXa/wormhole/blob/master/README.md#sw

**Comment by philfreo** [comment]
Why aren't SharedWorkers enabled/used by default?

**Comment by RubaXa** [comment]
@philfreo In my experience, SharedWorker does not work stably.

**Comment by philfreo** [comment]
If you have any more details about that I'd be very interested.

P.S. Check your email :)
