### ISSUE TITLE
UDID "incorrect"

### ISSUE THREAD

**Issue by mdeweerd** [RubaXa/wormhole#7]
Hi
I stumbled on your library and looked at your UDID function out of curiosity.
For info, the number is incorrectly generated.  It should respect this:
https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

-> Some of the bits are not random to indicate that the UDID is generated from random numbers!

Apparently the russian version of wikipedia is not as detailed.

**Comment by mdeweerd** [comment]
Very old ticket - not expecting this to be implemented.

**Comment by RubaXa** [comment]
Because it did not affect anything, and you yourself would send PR ;]

**Comment by mdeweerd** [comment]
I am not yudging - just cleaning up my backlog of 'issues'.
I did not indicate I was going to submit a PR. At the time I was just looking around for implementations.
I noticed that the standard was not followed which in itself can have an impact as the static bits are there for a reason.
But basically I am just cleaning my list now.
