### ISSUE TITLE
SharedWorkers seem perpetually disabled?

### ISSUE THREAD

**Issue by charliewolf** [RubaXa/wormhole#8]
[Here on line 12](https://github.com/RubaXa/wormhole/blob/e110d31b430b9b57d4ae457c15e0ae48c989f172/src/module.js#L12), this seems like it will always end up being `false`. I don't see anything that would set `window.wormhole` or `wormhole.workers` in the rest of the codebase. Is this intentional?

**Comment by RubaXa** [comment]
Yes, `SharedWorker` — not enabled by default.
To enable it, before include the library you need to declare:
```html
<script>window. wormhole = {workers: true};</script>
<script src="/vendor/wormhole.js"></script>
```

**Comment by charliewolf** [comment]
Hmm, I tried that but it appears this doesn't work if you're using RequireJS rather than just loading wormhole globally. Would you be open to a PR that allows whether workers are allowed as an argument to `Hole`?
